export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  BUSINESS_RULE_ERROR: "BUSINESS_RULE_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
